### ISSUE TITLE
File is not being tagged when uploaded via public link

### ISSUE THREAD

**Issue by atretyakovAgoda** [nextcloud/files_automatedtagging#1013]
### Bug description

Seems tagging of files does not work if a file was uploaded through shared link anonymously.
If a file is uploaded through GUI then it is tagged. So the problem when file is uploaded anonymously through shared link.

### Steps to reproduce

1. Create an automatic tagging flow: tag file with images mime type
2. Create and share a folder to public upload
3. Upload an image file through that link

### Expected behavior

File is tagged.

### Nextcloud Server version

27

### PHP engine version

PHP 8.2

**Comment by nickvergessen** [comment]
27 is no longer supported.
Please upgrade to a newer version and try again.
I just checked the newest version 30 and I can not reproduce your issue there.
