### ISSUE TITLE
Can I please get some "or" logic

### ISSUE THREAD

**Issue by Luticus** [nextcloud/files_automatedtagging#138]
Currently we can only use "and" logic.  So if I wanted to tag all possible mimetype text documents I'd currently have to create a flow for each mimetype, which is silly.  I should be able to create a single flow for example:

[mimetype || mimetype2 || mimetype3 ] => tag "text"

**Comment by nickvergessen** [comment]
You can use a regex with /(mimetype1|mimetype2|...)/
