### ISSUE TITLE
[Enhancement] and/or, Import/Export

### ISSUE THREAD

**Issue by cfranz** [nextcloud/files_automatedtagging#142]
Hello all,

I have two suggestions for some enhancements but I don't know where to submit them. That's why I'm posting it here.

**1. and/or**
Currently the standard conjunction for the different rules in a flow is "and". Sometimes it is helpful to choose an "or". I tried to add a rule to tag all excel-sheets and learned that there are 9 possible mime types for them. Currently I need to add 9 different flows to reach the goal. It would be nice to habe only one flow that uses "or" to have all mime types for excel in it.

**2. Export/Import**
It would be nice to have the option of importing and exporting flows. Currently I'm setting up a new installation making heavy use of tags and automated tagging. Afterwards I'd like to use these tags also in another existing installation. At the moment I have to do the work of configuring the flows again. Importing and exporting would save me a lot of time. Furthermore it would be possible to create a "flow repository", where users can find flows from other users and import them into their installation.

**Comment by dirdi** [comment]
If you introduce an additional "or" operator you need to define operator's precedence as well.

Consider the following example:
`filter1 and filter2 or filter3`

Depending on the operator precedence this could either be interpreted as
`(filter1 and filter2) or filter3` or as `filter1 and (filter2 or filter3)`

With this said, I think an additional operator would add more confusion than it is worth.

**Comment by nickvergessen** [comment]
1. You can do that with the regex option

2. Sounds like a good idea but should be treaten in another ticket

**Comment by cfranz** [comment]
Thank you for your responses. The problem with the precedence makes sense to me, so I will give the regex a try. For the second request I've opened a new ticket #160.
