### ISSUE TITLE
Missing Additional "When" Criteria

### ISSUE THREAD

**Issue by dirdi** [nextcloud/files_automatedtagging#158]
### Steps to reproduce
1. Create new flow: "Flow > Automated tagging / Add new flow"
2. Click on "When" criteria

### Expected behaviour
Other criteria like "File updated" or "File is uploaded" should be selectable, like in [Frank's presentation](https://www.youtube.com/watch?v=U-hhS0hiUAI):
![3](https://user-images.githubusercontent.com/7914030/74933111-9e7e9980-53e3-11ea-8036-cabf92d05a47.png)

### Actual behaviour
"File is accessed" is the only available "When" criteria. Nothing happens when clicked on:
![2](https://user-images.githubusercontent.com/7914030/74933231-dab1fa00-53e3-11ea-9c4b-810e77315edc.png)

### Server configuration

**Database:** mysql 5.7.29

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.1

**Where did you install Nextcloud from:** `nextcloud-18.0.1.zip` archive file.

**List of activated apps:**
![1](https://user-images.githubusercontent.com/7914030/74933704-ddf9b580-53e4-11ea-993a-d5d1a1f5e694.png)

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
```
$ dpkg -l | grep firefox
ii  firefox                               73.0-1                               amd64        Mozilla Firefox web browser
```

**Operating system:**
```
$ uname -a
Linux laptop 5.4.0-3-amd64 #1 SMP Debian 5.4.13-1 (2020-01-19) x86_64 GNU/Linux
```

**Comment by juliushaertl** [comment]
This is expected behavior. The files_accesscontrol app only operates on the one "file access" event since it kicks in earlier in the request cycle, before the file is being acessed. Other events like the file write event would not work here since they are emitted after something got written to the file and therefore would not work to block the request to write to a file.

**Comment by juliushaertl** [comment]
Sorry, I mixed up the repositories as your question is about files_automatedtagging. But the reason is similar. The tagging happens whenever the filecache gets updated, so there is ccurrently no way to limit that to a specific event.

**Comment by juliushaertl** [comment]
The screenshot was most likely done in a preview version where the events were not limited by yet by accident. See https://github.com/nextcloud/files_automatedtagging/commit/fa601a08f4b3e1099d9da646aa97b2db0bfa2b8d#diff-7197988778a490fda030ad64f8f31277

**Comment by dirdi** [comment]
Thanks for your fast response!

Just for clarification: Did I got this right that the "file access" event comprises all other events and therefore will be triggered e.g. if a file was created, uploaded etc.?

**Comment by juliushaertl** [comment]
Yes, thinking about it "File is accessed" is probably not the best descriptive term here, maybe we should go more with something like "File modified" since it is not triggering on read access but whenever the file metadata changes (size, last modified, ...) so on create and update.

**Comment by dirdi** [comment]
Any (Dev)Op will understand why it was phrased like it was but indeed, it is not intuitive but misleading. I think the most accurate *nix-ish phrase would be "File [touched](https://manpages.debian.org/buster/coreutils/touch.1.en.html)".

However, at least it should be documented.

**Comment by juliushaertl** [comment]
@jancborchardt Any idea for some better naming of that?

**Comment by meaz** [comment]
file changed?

**Comment by jancborchardt** [comment]
Yep, "File changed" is the simplest and easiest to understand language there. :)

**Comment by PlanetSmasher** [comment]
Maybe it can be extended with an Mouse-Hover Text for a more descriptive Infobox like: 

> This condition triggers at any created, uploaded, modified file.

**Comment by mmaridev** [comment]
I figured out I can tag a file when it's uploaded via upload file size > 0, is there any way to tag a file when it's created in NextCloud?

**Comment by ShapeShifter499** [comment]
> I figured out I can tag a file when it's uploaded via upload file size > 0, is there any way to tag a file when it's created in NextCloud?

I came across this while searching for a solution. I didn't think to enable ``upload file size > 0`` which is good for me because I wanted a "OCR" tag for uploaded PDFs so they would get processed by 'workflow_ocr'

But shouldn't it get triggered on any file that's created or modified without a "upload size" condition? @mmaridev
