### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/files_automatedtagging#2]
@jancborchardt can you create one?
Maybe something like a combination of 🔖 + the default icon combined?

**Comment by jancborchardt** [comment]
Just use the same icon as for the tags app. Simply copy it over. :)

**Comment by nickvergessen** [comment]
l, will do.

Can you create the "firewall" one thou? https://github.com/nextcloud/files_accesscontrol/issues/2

**Comment by nickvergessen** [comment]
Closed with #1
