### ISSUE TITLE
automated tagging slows down file upload to Group folder

### ISSUE THREAD

**Issue by liejuntao001** [nextcloud/files_automatedtagging#214]
### Steps to reproduce
1. use curl to upload a small file to various kinds of folders.
Following the instruction here: https://docs.nextcloud.com/server/latest/user_manual/files/access_webdav.html#accessing-files-using-curl

Use's default folder
Group Folder

2. If there is automated tagging rule for the folder, there is a long delay after the network transfer has finished.
3. The deeper the file is put into the folder structure, the longer is the delay.

The problem does not happen with a normal folder (like the Documents folder of every user)

Automated tagging rule:
File system tag is tagged with retention-parent
AND
File Mime type is not unix/httpd/unix-directory
Automated tagging retention

File size to upload: 54k

No automated tagging rule:
Group folder
real    0m0.874s

Apply automated tagging rule:
Use's default folder - 
real    0m0.959s

Group folder - directly in the folder
real    0m36.310s

Group folder - one level of sub-folder
real    0m44.328s

Group folder - two levels of sub-folder
real    0m50.683s

### Expected behaviour
Keep the slowdown in accepted range

### Actual behaviour
...

### Server configuration

**Operating system**: Ubuntu 18,04

**Web server:** Apache2.4

**Database:** Postgresql 10

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Where did you install Nextcloud from:**

**Signing status:**

**Comment by juliushaertl** [comment]
Thanks for the detailed report. Definitely something to profile at some point to see where the actual slow down is happening.

**Comment by Artheriom** [comment]
Hi,

I am currently facing the same issue on my server. I've done a few searchs, and the line who stuck a long time seems to be line 98 in `Operation.php` file : `$this->objectMapper->assignTags($fileId, 'files', explode(',', $match['operation']));` in `checkOperations`. Logs (I've put logs into the while loop, so it is definitively not a loop issue) : 

```
[Sun Feb 21 16:50:01.303456 2021] [php7:notice] [pid 25089] [client 192.168.10.6:59024] log before objectMapper->assignTags, referer: https://xxxxxxxxx/index.php/apps/files/?dir=/shared&fileid=30176
[Sun Feb 21 16:50:50.293028 2021] [php7:notice] [pid 25089] [client 192.168.10.6:59024] log after objectMapper->assignTags, referer: https://xxxxxxxx/index.php/apps/files/?dir=/shared&fileid=30176
```

The lag happens only the first time this method is called. Subsequent calls are fast. 

Hope it could help, if you need more logs, tell me :-)

**Comment by nickvergessen** [comment]
There have been some fixes related to grouipfolders in the meantime.
If this is still not working properly for you, feel free to create a new issue
