### ISSUE TITLE
not working with iOS Client 2.16 (00012)

### ISSUE THREAD

**Issue by berho** [nextcloud/files_automatedtagging#22]
### Steps to reproduce
1. Create rule in workflow: User-Agent is "iOS Client" Tag with "iOS  Uploads (hidden)"
2. Upload file to NextCloud with iOS Client
3. check tags

### Expected behaviour
Tag "iOS Uploads" set to file. (Sure, I log in as administrator ;)

### Actual behaviour
tag on file not set

### Server configuration
**Operating system**: linux

**Web server:** apache 

**Database:** MySQL 5.5.53

**PHP version:**  7.0.15

**Nextcloud version:**  11.0.1

**Where did you install Nextcloud from:** official download

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
contacts
files_markdown
direct_menu
audioplayer
twofactor_backupcodes
templateeditor
sharebymail
lookup_server_connector
logreader
firstrunwizard
files_videoplayer
files_versions
files_automatedtagging
files
calendar
user_ldap
password_policy
gallery
federation
external
user_saml
user_external
updatenotification
systemtags
survey_client
serverinfo
provisioning_api
files_sharing
files_retention
admin_audit
activity
workflowengine
theming
notifications
nextcloud_announcements
files_trashbin
files_texteditor
files_pdfviewer
files_external
files_accesscontrol
federatedfilesharing
encryption
dav
comments
bookmarks
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'idididididid',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'hopf.at',
  ),
  'datadirectory' => '/data',
  'overwrite.cli.url' => 'https://****/',
  'overwriteprotocol' => 'https',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => 'nicetry',
  'dbhost' => 'mydbhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'cloudadmin',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'updater.release.channel' => 'stable',
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** -

### Client configuration
**iOS App:** 2.16 (00012)

**Operating system:** iOS 10.2.1

#### Nextcloud log (data/owncloud.log)
```
no log entry while uploading files from iOS Client
```

**Comment by nickvergessen** [comment]
Right, the user agent of the iOS app was changed.
You can apply these changes to fix the issue:
https://github.com/nextcloud/server/pull/3431/files
