### ISSUE TITLE
Files from App "Text" are not tagged automatically

### ISSUE THREAD

**Issue by sbernhard** [nextcloud/files_automatedtagging#279]
### Steps to reproduce
1. Install App Text (https://github.com/nextcloud/text)
2. Set tagging rule like /^https:\/\/.*\/remote\.php\/webdav\/.*Transfer\/.*/ to tag with XYZ
3. Create a File in the Folder "Test Transfer" called "blub.md"

### Expected behaviour
Tag XYZ is set to "blub.md"

### Actual behaviour
no tags set to "blub.md"

In case of uploading a file to folder "Test Transfer" this works. 

### Server configuration
Nextcloud 18.0.6
Files automated tagging	1.8.3
Text	2.0.0
PHP Version: 7.3.19
pgsql Version: PostgreSQL 10.12

**Comment by nickvergessen** [comment]
Don't tag based on URLs. Instead tag the parent folder and make your rule work based on that system tag:
https://docs.nextcloud.com/server/19/admin_manual/file_workflows/access_control.html#denying-access-to-folders
