### ISSUE TITLE
Add screenshot to app store entry

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/files_automatedtagging#28]
@LukasReschke can you take a screenshot of a configuration which makes sense (I have no idea) and add it to the app store entry at https://apps.nextcloud.com/apps/files_automatedtagging

The same screenshot we can then use for the readme as well.

**Comment by LukasReschke** [comment]
> of a configuration which makes sense (I have no idea) 

Me neither.

cc @jospoortvliet 😉  – all others have one 🙈

**Comment by Schmuuu** [comment]
Hi everyone,

I created a screenshot which I would like to offer. I cannot (or at least don't know how to) upload the screenshot to the app in the store. 
So please feel free to use and edit it as needed:
https://cloud.our-box.net/s/BLOdH3o7MooKnZR

**Comment by jancborchardt** [comment]
@Schmuuu great, thank you! :) If you like, you can add it to this repository in the "img" folder as screenshot.png

Then the maintainer of this app needs to add it as screenshot and prepare a new release.

**Comment by nickvergessen** [comment]
There is a screenshot since july:
https://github.com/nextcloud/files_automatedtagging/blob/master/docs/screenshot.png

It will appear when we make the 13 release
