### ISSUE TITLE
No tag applied on anonymous upload to folder shared as file drop

### ISSUE THREAD

**Issue by NemoBarbarossa** [nextcloud/files_automatedtagging#30]
When I share a folder via link as a file drop to an external anonymous user and I upload a file through this link, it does not get tagged.
If I, at the same time, upload a file as the folder owner through the normal nextcloud interface, it gets tagged correctly.
We want to set a workflow to automatically set a retention tag to all files uploaded by external persons through that link.
We use the retention and automatedtagging apps that come shipped with Nextcloud.

### Steps to reproduce
1. set up tags for a folder containing files to be deleted automatically
2. set up tag for files to be deleted
3. define workflow to set the file tag (step 2) for uploaded files in a folder tagged with the folder tag (step 1)
4. share a folder through a link as file drop
5. open link and upload file

### Expected behaviour
Anonymously uploaded file should be tagged with the deletion tag (Step 2)

### Actual behaviour
File does not get tagged

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.18

**PHP version:** php 7.0.15

**Nextcloud version:** 11.0.3

**Where did you install Nextcloud from:** .tar from nextcloud website

**Signing status:**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_u2f: 1.2.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_external
  - templateeditor
  - user_saml

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "oc04vzf9fpuk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "priv IP",
            "domain.ext",
            "domain.int"
        ],
        "datadirectory": "\/opt\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/privIP\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "singleuser": false
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Chrome 57.0.2987.133

**Operating system:** Windows 10 Pro 1703

#### Nextcloud log (data/owncloud.log)

No entries in log according to the upload, the tags or the workflows

**Comment by nickvergessen** [comment]
Thanks for the report, I made a patch at https://github.com/nextcloud/server/issues/4792
However I'm not sure that is entirely correct, so wait for the expert to confirm, before putting that patch live.
