### ISSUE TITLE
missing setting at NC 12.0.0

### ISSUE THREAD

**Issue by nesnera** [nextcloud/files_automatedtagging#35]
### Steps to reproduce
1. Intall NC 12.0.0
2. enable or re-enable "Files automated tagging" (as admin Settings > Apps > navigate to app and press "Enable"
3. under Settings > Admin > Additional settings should be [this settings](https://github.com/nextcloud/files_automatedtagging/blob/master/docs/screenshot.png) but isn't :(

### Expected behaviour
clear

### Actual behaviour
clear

### Server configuration

**Operating system**:
CentOS Linux release 7.3.1611 (Core)
**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Apr 12 2017 21:03:28
**Database:**
postgres (PostgreSQL) 9.2.18
**PHP version:**
PHP 7.0.20 (cli) (built: Jun 10 2017 06:34:07) ( NTS )
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Where did you install Nextcloud from:**
[this How to | last week](http://www.marksei.com/install-nextcloud-12-centos-7/)
**Signing status:**
??
```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
"This site can’t be reached" :(

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - checksum: 0.3.5
  - comments: 1.2.0
  - dav: 1.3.0
  - defaultgroup: 0.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_saml: 1.3.2
  - workflowengine: 1.2.0
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocqutmgwx5s9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "soubory.otevrenamesta.cz",
            "[2a01:430:17:1::ffff:689]"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/soubory.otevrenamesta.cz\/nextcloud",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "otevrenamesta.cz",
        "maintenance": false
    },
    "apps": {
        "DefaultGroup": {
            "ignore_groups": "[]",
            "default_groups": "[\"all\"]",
            "login_hook": "false"
        },
        "activity": {
            "installed_version": "2.5.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "admin_audit": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "15"
        },
        "bruteforcesettings": {
            "installed_version": "1.0.2",
            "types": "",
            "enabled": "yes"
        },
        "checksum": {
            "installed_version": "0.3.5",
            "types": "filesystem",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1501202625.4649",
            "vendor": "nextcloud",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "installed.bundles": "[\"CoreBundle\"]",
            "oc.integritycheck.checker": "[]",
            "lastupdateResult": "[]",
            "umgmt_send_email": "true",
            "umgmt_show_last_login": "true",
            "scss.variables": "cb987e70e604abe4c1d4b9e9597bcb5b",
            "lastupdatedat": "1501603376",
            "umgmt_show_backend": "false",
            "umgmt_show_storage_location": "false",
            "lastcron": "1501604560"
        },
        "dav": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "defaultgroup": {
            "installed_version": "0.3.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.2.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.7.2",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_accesscontrol": {
            "installed_version": "1.2.4",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_automatedtagging": {
            "installed_version": "1.2.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_downloadactivity": {
            "installed_version": "1.1.1",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_pdfviewer": {
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "outgoing_server2server_share_enabled": "no"
        },
        "files_texteditor": {
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.5.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.1.0",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.1",
            "types": "logging",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "17.0.0",
            "types": "",
            "enabled": "no"
        },
        "groupfolders": {
            "installed_version": "1.1.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.1",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notifications": {
            "installed_version": "2.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "richdocuments": {
            "installed_version": "1.12.34",
            "enabled": "no",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes",
            "update_check_errors": "0"
        },
        "user_saml": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.3.2"
        },
        "workflowengine": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Chromium 59.0.3071.104 Fedora Project
**Operating system:**
Fedora release 25 (Twenty Five)
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
I don't know how upload it

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
I have no idea how to obtain it.

**Comment by nickvergessen** [comment]
Its in the workflow section 😉

**Comment by nesnera** [comment]
Yes, it is. :D
