### ISSUE TITLE
New condition "local folder"

### ISSUE THREAD

**Issue by besim** [nextcloud/files_automatedtagging#39]
I'm using the Owncloud/Nextcloud plugin with Thunderbird to outsource large attachements to my Nextcloud installation. For this webdav-based uploads I reserved a folder named "filelink" - all thunderbird-specific uploads are going into this folder.

It would be nice to set up an rule with your plugin to catch all files which are uploaded to a specific Nextcloud folder. So I would be able to mark all uploaded files to this folder with an special label.

My intention is marking them with a label which I have set up with the plugin "File Retention" to delete those marked files automatically after a specific time.

**Comment by nickvergessen** [comment]
You can already do this with the "System tags" rule,
it's even the example in the docs 😉 
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/automated_tagging.html#assigning-restricted-and-invisible-tags
