### ISSUE TITLE
File Size Based Tagging Not Working With Android App

### ISSUE THREAD

**Issue by spirkinator** [nextcloud/files_automatedtagging#403]
Automated tagging of files based on file size works fine when uploading/syncing via the desktop client and web interface, but not when uploading with the Android app.  My other flow used to tag files based on file extensions (e.g. zip), works fine when uploading files that match the tagging rule using the Android app, desktop client, and web interface.

### Steps to reproduce
1.  Create a Restricted Collaborative Tag named "Large File (50MB+)" as the ncp user in Settings -> Administration -> Basic Settings
2.  Setup flow as the ncp user in Settings -> Administration -> Flow:
- When file is changed
- and File Size (Upload) greater or equals 50 MB
- Automated Tagging as "Large File (50MB+)" tag created in step 1.
- ![Screenshot 2021-02-15 00-52-45](https://user-images.githubusercontent.com/67397983/107924805-693e5600-6f28-11eb-8a97-83fd0c21ce91.png)

3.  Using a normal user account (not the ncp account), upload a file larger than 50MB using either Automatic Upload or manual upload in the NextCloud app, or share to NextCloud from another app

### Expected behaviour
Files that are above 50MB should be tagged with the "Large File (50MB+) tag.

### Actual behaviour
The file size based tag is not applied.
 - 
![Screenshot 2021-02-15 01-07-52](https://user-images.githubusercontent.com/67397983/107926237-4d3bb400-6f2a-11eb-9ae6-52c67e13f815.png)

### Server configuration
**Operating system**:  
Raspbian GNU/Linux 10 (buster)

**Web server:**
apache2/stable,now 2.4.38-3+deb10u4 armhf

**Database:**
mariadb-server-10.3/stable,now 1:10.3.27-0+deb10u1 armhf

**PHP version:**
php7.3/stable,now 7.3.19-1~deb10u1 armhf

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.4 on NextCloudPi v1.34.7

**Files automated tagging app version:**
1.10.1

**Where did you install Nextcloud from:**
https://raw.githubusercontent.com/nextcloud/nextcloudpi/master/install.sh 

### Client configuration
Nextcloud Android App version 3.15.0

**Operating system:**
Android 8.0

**Comment by nickvergessen** [comment]
If you can still reproduce this with a recent version, please report a bug in https://github.com/nextcloud/server/issues as that is where the size check lives.
