### ISSUE TITLE
File is locked after upload due to automated tagging

### ISSUE THREAD

**Issue by stephan-a** [nextcloud/files_automatedtagging#41]
### Preconditions
There must be a rule group configured in the Admin interface / "Files automated tagging" which adds the tag "Large file" to files with a filesize greater than 25 MB (so one rule in the rule group is enough).

### Steps to reproduce
1. Login with user-1, create a directory "share-1" and share it with user-2
2. Login with user-2, open "share-1", create a directory "share-2" within "share-1" and share it with user-3
3. Login with user-3, open "share-2" and upload a file "Test-file.msi" with a filesize greater than 25 MB within "share-2"

### Expected behaviour
The file gets uploaded successfully and is automatically tagged with the tag "Large file".

### Actual behaviour
- An error notification "Locked" shows up in the header
- Error message in log: Fatal / webdav / OCA\DAV\Connector\Sabre\Exception\FileLocked: "share-2/Test-file.msi" is locked
- Afterwards it's not possible to upload this file again, until the lock is manually deleted from the table "oc_file_locks"

When the rule group is deleted from the Admin interface / "Files automated tagging" everything works as expected.

The upload of files which does not match the rule condition are not affected.

### General server configuration

**Operating system:** Ubuntu 16.04.3 LTS

**Web server:** Apache/2.4.18

**Database:** MySQL 5.7.20

**PHP version:** 7.0.22
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from v11.0.3

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - announcementcenter: 3.1.0
 - audioplayer: 2.1.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - drawio: 0.8.8
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_antivirus: 1.1.0
 - files_automatedtagging: 1.2.2
 - files_clipboard: 0.6.4
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_notifications
 - direct_menu
 - federation
 - files_external
 - firstrunwizard
 - sharebymail
 - socialsharing_email
 - spreed
 - survey_client
 - theming
 - theming_customcss
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "debug": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "loglevel": 0,
    "maintenance": false,
    "updater.release.channel": "beta",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "default_language": "en",
    "defaultlanguage": "en",
    "trusted_proxies": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR"
    ],
    "updatechecker": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "skeletondirectory": "",
    "appstoreenabled": true,
    "singleuser": false,
    "overwriteprotocol": "https",
    "theme": "***REMOVED SENSITIVE VALUE***",
    "mail_template_class": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "lost_password_link": "disabled"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

### Logs

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
OCA\DAV\Connector\Sabre\Exception\FileLocked: "share-2/Test-file.msi" is locked
[internal function] OCA\DAV\Connector\Sabre\LockPlugin->getLock(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/path/to/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/path/to/nextcloud/apps/dav/appinfo/v1/webdav.php - line 76: Sabre\DAV\Server->exec()
/path/to/nextcloud/remote.php - line 162: require_once('/path/to/nextcl...')
{main}
```
</details>

<details>
        <summary>Browser log</summary>

```
PUT https://cloud.domain.com/remote.php/webdav/share-2/Test-file.msi 423 (Locked)

Response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"share-2/Test-file.msi" is locked</s:message>
</d:error>
```
</details>

**Comment by gcleaves** [comment]
I have the same problem. This bug defeats the purpose of the App, unfortunately, since auto-tagging makes the system unusable. The strange thing is, I'm sure this was working properly at one point. I've had to disable the rules and can now upload without issue.

**Comment by Charburner** [comment]
I'm experiencing the same issue every time I try to update our Nextcloud instances from 11.0.2 to 12.0.X and from there to 13.0.X. As long as the files_automatedtagging app is enabled, the whole system becomes unusable since we cannot exchange files with our customers. 

We use an invisible tag which gets assigned to each new file uploaded by a customer group. Later on, after a certain period of time, those tagged files will be deleted automatically via the Retention app. Due to the "bug" all files, that should be tagged, are just locked forever. I tried APCu, Redis, no filecaching, no filelocking, nothing helps.

Is there any solution or workaround instead of disabling the whole app?

**Comment by nickvergessen** [comment]
I just tested the steps from the first post, both on 13 and 14,  and they work just fine.

**Comment by Charburner** [comment]
I could imagine it only happens after updating. My  steps would be:

1. Have an Nextcloud 11.0.2 instance where User A shares a folder structure (with several folders below) with User B.
2. Use the files_automatedtagging app to tag all new files uploaded by non admins so they can be deleted after 30 days via Retention app.
3. Update to Nextcloud 12.0.11 (and 13.0.X) and try to upload files or create folders as User B.
4. Realize that you can do this in your own first (root) level and also in the first shared folder, which User A initiated earlier on.
5. BUT as soon as you try to create folders or upload files below that 2nd level (in a subdirectory of the shared folder), these objects will be locked by filecaching and all user actions like downloading or deleting will be prevented.

I'm sorry but I currently have absolutely no clue how to dig into this issue :(

**Comment by gcleaves** [comment]
> I just tested the steps from the first post, both on 13 and 14, and they work just fine.

Hi @nickvergessen. My case is /Customers shared with 2 users so that employees can upload files into /Customers/A, /Customers/B, /Customers/D-Z. /Customers/A is shared with user A, /Customers/B is shared with userB, etc. Maybe this could help debug the issue.

**Comment by nickvergessen** [comment]
Closing stale issue
