### ISSUE TITLE
Make the filename available for selection as rule criteria

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/files_automatedtagging#42]
Currently it's not possible to select the filename as a criteria for a rule. Filename seems like a pretty common criteria for many workflow use-cases, so it would be great if it could be added (beside file size, file mime type and file system tag).

<img width="1120" alt="screen shot 2017-11-17 at 16 22 14" src="https://user-images.githubusercontent.com/295122/32954745-41a55d02-cbb4-11e7-9bbf-6d75b40a61aa.png">

**Comment by nickvergessen** [comment]
Duplicate https://github.com/nextcloud/server/issues/7136

**Comment by mathiasconradt** [comment]
Sorry for the duplicate, I had just checked for open issues in this app.

**Comment by nickvergessen** [comment]
No problem 👍
