### ISSUE TITLE
Logic error with multiple conditions

### ISSUE THREAD

**Issue by joesch2** [nextcloud/files_automatedtagging#452]
I use Nextcloud 20.0.9 and have defined the following process:

![grafik](https://user-images.githubusercontent.com/18378305/116406980-8b5e2980-a831-11eb-822f-c459c783472e.png)

If I change a file, the tag "Löschfrist" is set even if the tag "bezahlt" has not been set.

Many thanks, Jörg

**Comment by jacotec** [comment]
Might be related to #423

**Comment by nickvergessen** [comment]
Please note that it is enough for any parent to contain a tag, for the rule to match.

So in your case if a folder has "bezahlt" and a file inside has "Rechnungseingang", the file will on modification also get the tag "Loschfrist 10 Jahre".

If there is still an issue with Nextcloud 25 or later, feel free to create a new more detailed report.
