### ISSUE TITLE
Add user agent: Outlook Add-in

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/files_automatedtagging#48]
The user agents doesn't have our Outlook Add-in in the list. It would be very useful to have it, so you can use auto-tagging and retention to remove attachments after a set time!

We'd need to know from Luc Pasmans what the user agent is, I suppose...

**Comment by nickvergessen** [comment]
Should also identify the thunderbird one if possible, but i can test that one myself

**Comment by usselite** [comment]
The add-in doesn't include a user-agent for now, I can add "Nextcloud Secure Sharing Outlook Add-in" or in case the add-in should have the same user-agent as the thunderbird add-in let me know.

**Comment by rullzer** [comment]
@usselite no it doesn't have to be the same one, actually it is better if they differ ;)

Maybe something like: "Nextcloud Secure Sharing Outlook Add-in/X.Y.Z" where X.Y.Z is the version.

**Comment by nickvergessen** [comment]
Best would be to keep it in line with the other agents we use. So I would propose:
* Outlook: `Mozilla/5.0 (<Operating System>) Nextcloud-Outlook v<Version>`
* Thunderbird: `Mozilla/5.0 (<Operating System>) Nextcloud-Thunderbird v<Version>`

Don't get confused because of the `Mozilla/5.0` that's the standard for formating of the user agents.

**Comment by usselite** [comment]
I added the proposed format as @nickvergessen mentioned. 

`Mozilla/5.0 (<Operating System>) Nextcloud-Outlook v<Version>`

Later today / this weekend I will distribute some new builds.

**Comment by nickvergessen** [comment]
Awesome

**Comment by jospoortvliet** [comment]
This works, we even blogged about it... ;-) Close?

**Comment by nickvergessen** [comment]
But only for Outlook, the issue on the thunderbird plugin is still open.

**Comment by blizzz** [comment]
Is the Thunderbird thing dead?

**Comment by lars-becker** [comment]
> Is the Thunderbird thing dead?

@blizzz Mostly, but there is a good alternative: <https://gitlab.com/joendres/filelink-nextcloud#cloud-filelink-for-nextcloud-and-owncloud>.

**Comment by nickvergessen** [comment]
If this is still an issue in Nextcloud 24 or later, please feel free to create a new issue in https://github.com/nextcloud/server/issues as that is where the "user agent" check code is
