### ISSUE TITLE
Feature request: Image metadata:keyword -> NC tags

### ISSUE THREAD

**Issue by nztvar** [nextcloud/files_automatedtagging#484]
IPTC's IIM headers provide opportunity to add 'tags' to image files. In particular, the keyword allows arbitrary tagging schema, is widely implemented (including in XMP) in photo capturing and processing, image editing, and gallery applications. 

With mobile clients' automated upload of images it seems this would be a natural feature of the automated tagging app.

References:

- IPTC Information Interchange Model: [Metadata Schema and Format Specification v4.2](https://www.iptc.org/std/IIM/4.2/specification/IIMV4.2.pdf)
  - [IPTC Photo Metadata Standard](https://www.iptc.org/standards/photo-metadata/iptc-standard/)
- Adobe's eXtensible Metadata Platform: [XMP specification](https://www.adobe.com/devnet/xmp.html)

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by blizzz** [comment]
This sounds like a use case, but it does not fit into this app. It would be better to have a seperate one that would allow to import/update the tags from images.
