### ISSUE TITLE
Location Tag

### ISSUE THREAD

**Issue by markymif** [nextcloud/files_automatedtagging#50]
Hi, is it possible to add a tag based on location?  I setup our users with a temporary folder where they can share files for say 7 days, so ideally be able to say if file is uploaded to "temporary folder" tag it as DeleteIn7Days

**Comment by nickvergessen** [comment]
Yes, that is exactly covered in our docs:
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/automated_tagging.html
