### ISSUE TITLE
Language on admin page does not respect profile settings

### ISSUE THREAD

**Issue by tflidd** [nextcloud/files_automatedtagging#51]
### Steps to reproduce
1. Set your browser default language to a different to the one than your profile language on Nextcloud
2. Go to the admin page of automated tagging

### Expected behaviour
Show the whole admin page in the same language (profile language).

### Actual behaviour
On the workflow section of the admin page, the automated tagging is shown in french (browser default) and not in the profile language (English)
![screenshot workflow](https://user-images.githubusercontent.com/8111200/40310770-2edd9d88-5d0e-11e8-9ddb-3ecb3942bd02.png)

### Server configuration
**Operating system**: Debian/PHP7

**Nextcloud version:** 12.0.6

Tagging app: 1.2.2

**Comment by nickvergessen** [comment]
Can not reproduce any more, so I will close this.
If it till happens for you, feel free to reopen.
