### ISSUE TITLE
Define Request URL

### ISSUE THREAD

**Issue by hoangdmps02770** [nextcloud/files_automatedtagging#52]
I'm using Nextcloud 13.0.2 and Autotagiing 1.3.0 . I want to tag the file based on which directory the file in. For example, when I upload a file into "2017" folder, it will automatically tag the file with the tag "2017". I found a feature which is called " Request URL " but I can't barely understand how to define that kind of URL. But I have tried http://domain.com/nextcloud/index.php/apps/files/?dir=/TEST but it doesn't work.
Thank you

**Comment by nickvergessen** [comment]
Well the folder name is not part of the URL when the upload happens.
So you have to use the tagging feature.

Please see https://docs.nextcloud.com/server/12/admin_manual/file_workflows/access_control.html#denying-access-to-folders for an example with the access control app, but it works the same way with tagging.
