### ISSUE TITLE
Feature Request: Folder Tagging

### ISSUE THREAD

**Issue by TheACF** [nextcloud/files_automatedtagging#545]
Please delete if feature requests are note wanted here.
I would request if it is planned to get the possibility to automate also the folder tagging. Additional, it would be fine to set a rule with folder context, for example: "If a file is uploaded in this folder, set the tag xxx to the folder"

**Comment by blizzz** [comment]
Generally it possible to tag files and folders, but not by hard coded paths (that may be different when acting on files and folders shared to users)

**Comment by meonkeys** [comment]
I'm hearing a feature request to tag files according to a rule *when they are uploaded to a particular folder*.

Can we update the title of this feature request? Suggestion: "Feature Request: tag files uploaded to a particular folder".

**Comment by meonkeys** [comment]
Also, is this a dup of #219?

**Comment by nickvergessen** [comment]
Closing as per above
