### ISSUE TITLE
same regexp does not work with file_automatedtaging but does with workflow automated scripts app

### ISSUE THREAD

**Issue by stephanhendl** [nextcloud/files_automatedtagging#547]
### Steps to reproduce
Filename is "yymmdd.pdf" which is covered by this regexp `/^{d{6}\.pdf$/i` It was checked via [https://regex101.com/](https://regex101.com/) but the App says "Configuration is invald bcause regexp is wrong."

![image](https://user-images.githubusercontent.com/18658366/159430741-7407d954-ac1a-4c3a-a2b6-b2880f973b79.png)

### Expected behaviour
Regexp should work.

### Actual behaviour
Regexp does not work.

### Server configuration

**Operating System:**: Debian 10

**Webserver:** Nginx-1.14.2

**Database:** Mariadb-10.3-31

**PHP version:** php7.4-fpm

**Nextcloud version:** 22.2.6.2

**Where did you install Nextcloud from:** php updater.phar

**Signing status:** ok

**List of activated apps:**

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - calendar: 3.2.2
  - checksum: 1.1.3
  - circles: 22.3.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.8
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.6
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_automatedtagging: 1.12.0
  - files_external: 1.13.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.1
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.4
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.1
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.2
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_script: 1.7.0
  - workflowengine: 2.4.0
Disabled:
  - encryption

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "...",
            "...",
            "...",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/...\/nextcloud",
        "dbtype": "mysql",
        "version": "22.2.6.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "...",
        "proxyexclude": [
            "10.*",
            "*....",
            "*....",
            "...",
            "..."
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "2",
        "default_language": "de_DE",
        "defaultapp": "files",
        "updater.release.channel": "stable",
        "mail_sendmailmode": "smtp",
        "mysql.utf8mb4": true,
        "default_phone_region": "DE"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

**Comment by nickvergessen** [comment]
These rules are maintained in the server.
The app is only doing the tag selection part on the right half of the flow

**Comment by nickvergessen** [comment]
Also the rule saves fine here if I fix the little type: `/^\d{6}\.pdf$/i`
you posted `/^{d{6}\.pdf$/i` before (check the character before the d)

**Comment by stephanhendl** [comment]
I'm very sorry, but in the first line I posted: `/^\d{6}\.pdf$/i`. As you can see from screenshot - the regexp works with the "run_scripts" workflow but not with the "file_automatedtagging". Both regexp are identically
![files_automaticaltagging_regexp_error2](https://user-images.githubusercontent.com/18658366/160101171-66ad411a-71af-437c-b99d-8ede78406fcf.PNG)
.

**Comment by nickvergessen** [comment]
The problem is the Mimetype thing. There it says "entspricht" instead of "ist" for the first rule set which means it's trying to be a regex, but the value is a string with the mimetype of the PDF-Dokumente

**Comment by stephanhendl** [comment]
Ah ok, thank you. Now it works!
