### ISSUE TITLE
Review Readme file

### ISSUE THREAD

**Issue by tflidd** [nextcloud/files_automatedtagging#55]
I've just gone through the translation and found something which could be wrong in the Readme.md:

> To define tags, administrators can create and manage a set of rule groups. Each rule group consists of one or more rules combined through operators. Rules can include criteria like file type, size, time and more. A request matches a group if all rules evaluate to true. On uploading a file all defined groups are evaluated and when matching, the given tags are assigned to the file.

My problem is: I can use different rules and combine them through operators. Suppose, I use two rule and combine them with operator `or`. In this case, to match the group it is sufficient if one rule is true (due to the or condition). So the statement:

> A request matches a group if all rules evaluate to true.

only applies for `and` operators.

**Comment by nickvergessen** [comment]
You misunderstood the "operators" term.

It refers to "matches/greater than/..." for all the rules.
All rules are combined with `AND`, which is why it says "A request matches a group if all rules evaluate to true."
