### ISSUE TITLE
Unreleased file locks on tagged items

### ISSUE THREAD

**Issue by epfreese** [nextcloud/files_automatedtagging#562]
### Steps to reproduce
1. Enable Files automated tagging
2. Define Rules like those in the photo (file system access, mimetype not folder, tag "delete contents after ...")
3. Create a txt file in a folder tagged with "Delete contents ..."
4. Observe that folder contents are tagged with "Delete After ..."
5. Modify txt file
6. Observe that saving doesn't ever complete
7. Nextcloud log mentions exclusive lock errors

![image](https://user-images.githubusercontent.com/84100749/165116860-88b5b16d-6245-4b4b-91c8-21e1683a3440.png)

If Files Automated Tagging is disabled new files function appropriately.

### Expected behaviour
Tell us what should happen
Files should be tagged and modifiable

### Actual behaviour
Tell us what happens instead
Files are tagged and not modifiable

### Server configuration

**Operating system**:
Ubuntu 20.04

**Web server:**
nginx proxy in front of fpm

**Database:**
Postgresql

**PHP version:**
PHP 8.0.18 

**Nextcloud version:** (see Nextcloud admin page)
23.03

**Where did you install Nextcloud from:**
the official nextcloud:fpm-alpine image

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - encryption: 2.11.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_automatedtagging: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - terms_of_service: 1.9.3
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_domains": [
            "localhost",
            "REDACTED",
            "REDACTED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "simpleSignUpLink.shown": false,
        "skeletondirectory": "",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "1fa users"
        ]
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 91.8.0ESR
**Operating system:**
Windows 10 

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
[nclog.txt](https://github.com/nextcloud/files_automatedtagging/files/8555639/nclog.txt)

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Hmm, we don't create any locks when tagging things 🤔

**Comment by nickvergessen** [comment]
Also the lock happens during preview generation and automated tagging is not even doing something with previews.
Maybe it's a race condition or something?

In the meantime 23 is EOL, so in case you update and it's still happening in 25 only with autotagging, feel fee to create a new issue
