### ISSUE TITLE
Automatic file tagging still not works with S3

### ISSUE THREAD

**Issue by fetra1** [nextcloud/files_automatedtagging#63]
I can not tag files automatically. I have read that there are problems with object storages and automatic tagging but did not find any workarounds or fixes. There has been a similar issue which was closed with a link to a fix which seemed to not work. Is there still someone working at it?

### Steps to reproduce
1. Upload a file into my "home" (no groupfolder) which matches the criteria for automated file tagging
2. Check if the tags are applied

### Expected behaviour
The file is uploaded and tagged with the specified tag.

### Actual behaviour
The file is uploaded but even 15 minutes later no tags show up.

### Server configuration

**Operating system**: Ubuntu 18.04.1 LTS

**Web server:** Apache/2.4.29

**Database:** RDS by Amazon (MySql)

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14.0.3

**Where did you install Nextcloud from:** Updated from 13.0.5 to 14.0.3 with the web updater

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
No errors have been found.
```

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_automatedtagging: 1.4.0
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.1
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "isr-s3-bucket-nc",
                "autocreate": false,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "region": "eu-central-1",
                "use_path_style": false
            }
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "overwrite.cli.url": "https:\/\/nextcloud.isrcloud.io\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.isrcloud.io"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/skeletondirectory",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable"
    }
}
or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** S3 as primary storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Microsoft Active Directory

### Client configuration
**Browser:** Chrome 69.0.3497.100

**Operating system:** Windows 10

#### Nextcloud log (data/owncloud.log)
```
Nothing
```

#### Browser log
```
Insert your browser log here, this could for example include:
Nothing
```

**Comment by nickvergessen** [comment]
Which tagging rules did you configure?

**Comment by fetra1** [comment]
![image](https://user-images.githubusercontent.com/44575587/48115597-b7e9e980-e263-11e8-9c9c-6e264cc185ae.png)
We already migrated to EBS volumes instead of S3 because of several problems https://github.com/nextcloud/server/issues/11895. Tagging works without any problems here, so it should be something with the S3 implementation.

**Comment by fetra1** [comment]
When saving files to group folders it does not work as well, even without S3. After some research I found out that group folders does not support collaborative tags. It would be great if this could be implemented. I'm sure this would be great for file retention.

**Comment by nickvergessen** [comment]
Yeah, see https://github.com/nextcloud/files_accesscontrol/issues/96
