### ISSUE TITLE
Tagging  behaves differently on files/folders

### ISSUE THREAD

**Issue by aventrax** [nextcloud/files_automatedtagging#64]
### Steps to reproduce
1. Setup a "Request URL" rule on "Files automated tagging"  specifying "does not match" with the following regexp: `/^https\:\/\/cloud\.mydomain\.com\/remote\.php\/webdav\/Releases.*/i`. The tag assigned by this rule is _testtag_
2. Upload a folder into the "Releases" folder

### Expected behaviour
The files and sub folders into the _Releases_ folder shouldn't have any tag because of the exclusion rule  defined above.

### Actual behaviour
Files are NOT tagged -> Ok
Folders ARE tagged -> NOT OK

### Server configuration

**Operating system**: Debian 9.0

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.x

**Nextcloud version:** 14.0.3

**Where did you install Nextcloud from:** Upgraded on each stable release from ownCloud 8.

**List of activated apps:**
Enabled:                                
  - accessibility: 1.0.1                
  - calendar: 1.6.3                     
  - cloud_federation_api: 0.0.1         
  - comments: 1.4.0                     
  - contacts: 2.1.6                     
  - dav: 1.6.0                          
  - event_update_notification: 0.3.0    
  - federatedfilesharing: 1.4.0         
  - files: 1.9.0                        
  - files_automatedtagging: 1.4.0       
  - files_external: 1.5.0               
  - files_pdfviewer: 1.3.2              
  - files_retention: 1.3.0              
  - files_sharing: 1.6.2                
  - files_texteditor: 2.6.0             
  - files_videoplayer: 1.3.0            
  - logreader: 2.0.0                    
  - lookup_server_connector: 1.2.0      
  - nextcloud_announcements: 1.3.0      
  - notifications: 2.2.1                
  - oauth2: 1.2.1                       
  - password_policy: 1.4.0              
  - provisioning_api: 1.4.0             
  - serverinfo: 1.4.0                   
  - sharebymail: 1.4.0                  
  - support: 1.0.0                      
  - survey_client: 1.2.0                
  - systemtags: 1.4.0                   
  - theming: 1.5.0                      
  - twofactor_backupcodes: 1.3.1        
  - updatenotification: 1.4.1           
  - user_ldap: 1.4.0                    
  - workflowengine: 1.4.0               
Disabled:                               
  - activity                            
  - admin_audit                         
  - encryption                          
  - federation                          
  - files_trashbin                      
  - files_versions                      
  - firstrunwizard                      
  - gallery                             
  - user_external                       

**Are you using external storage, if yes which one:** Yes, using local storage mounted on /Releases

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Yes, LDAP

### Client configuration
**Browser:** Any

**Operating system:** Windows

**Comment by nickvergessen** [comment]
You should not try to match Folder names via URL pattern.
Starting Nextcloud 15 there is an option for the name of the new item (file/folder).

However note that when you upload a folder, that will only affect the folder in first place. The files are uploaded afterwards and therefor their name will be matched instead of the folder name.

**Comment by nickvergessen** [comment]
If you go the files app the last option on the left side is "Tags" when you select the tag there it should show all files/folders with the tag.
