### ISSUE TITLE
can's select tags rather then the 5 displayed

### ISSUE THREAD

**Issue by kintaro1981** [nextcloud/files_automatedtagging#645]
### Steps to reproduce
1. create more than 5 tags
2. create a auto tagging flow
3. you can select only from 5 tags.

### Expected behaviour
you should be able to select/search/filter any tag

### Actual behaviour
You can select/search/filter only one of the 5 displayed tags instead of any tag. 

### Server configuration

**Operating system**:
CentOs7
**Web server:**
nginx 1.17.1
**Database:**
mariadb 10.3.37
**PHP version:**
php 7.4.33
**Nextcloud version:** (see Nextcloud admin page)
25.0.2

**Comment by nickvergessen** [comment]
Fixed in newest 1.15.2 released just now
