### ISSUE TITLE
Automated tagging unable to save flow

### ISSUE THREAD

**Issue by VitoAliberti** [nextcloud/files_automatedtagging#747]
Save button not working when trying to configure a flow. Clicking the save button doesn't do anything. Tried different browsers and different admin accounts. Removed and added the app. tried removing and adding the app and rebooting.

[
![Save_button_not_working](https://github.com/nextcloud/files_automatedtagging/assets/134233940/6257a3aa-8ae3-45ea-a844-075e7c977b80)
](https://i.postimg.cc/wj2dpNJK/Save-button-not-working.png)

**Comment by nickvergessen** [comment]
Can you tell which version of Nextcloud and the app you are using?

Also can you open the browser console (Ctrl+F12) and see if there are any errors reported when you press the button?

**Comment by VitoAliberti** [comment]
Yes. App ver 1.10.1
Nextcloud ver. 20.0.14

Failed to save operation
(anonymous) @ Rule.vue:134
c @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
Y @ workflowengine.js?v=414a0b10-44:1
i @ workflowengine.js?v=414a0b10-44:1
Promise.then (async)
Y @ workflowengine.js?v=414a0b10-44:1
a @ workflowengine.js?v=414a0b10-44:1
(anonymous) @ workflowengine.js?v=414a0b10-44:1
(anonymous) @ workflowengine.js?v=414a0b10-44:1
saveRule @ Rule.vue:127
Re @ workflowengine.js?v=414a0b10-44:1
n @ workflowengine.js?v=414a0b10-44:1
o._wrapper @ workflowengine.js?v=414a0b10-44:1
workflowengine.js?v=414a0b10-44:1 TypeError: Cannot read properties of undefined (reading 'meta')
    at Rule.vue:135:1
    at c (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.e.<computed> [as throw] (runtime.js:97:21)
    at Y (workflowengine.js?v=414a0b10-44:1:1298960)
    at i (workflowengine.js?v=414a0b10-44:1:1299199)

**Comment by VitoAliberti** [comment]
TypeError: Cannot read properties of undefined (reading 'meta')
    at Rule.vue:135:1
    at c (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at forEach.e.<computed> [as throw] (runtime.js:97:21)
    at Y (workflowengine.js?v=414a0b10-44:1:1298960)
    at i (workflowengine.js?v=414a0b10-44:1:1299199)
Ue @ workflowengine.js?v=414a0b10-44:1
Xe @ workflowengine.js?v=414a0b10-44:1
He @ workflowengine.js?v=414a0b10-44:1
(anonymous) @ workflowengine.js?v=414a0b10-44:1
Promise.catch (async)
Re @ workflowengine.js?v=414a0b10-44:1
n @ workflowengine.js?v=414a0b10-44:1
o._wrapper @ workflowengine.js?v=414a0b10-44:1
xhr.js:184     POST https://172.24.1.54/ocs/v2.php/apps/workflowengine/api/v1/workflows/global?format=json 404 (Not Found)

**Comment by nickvergessen** [comment]
Nextcloud 20 is no longer supported. The oldest supported version is Nextcloud 25.0.6

**Comment by VitoAliberti** [comment]
> Nextcloud 20 is no longer supported. The oldest supported version is Nextcloud 25.0.6

When I check in Overview settings it says "You are running the latest version" 20.0.14
I don't have the option to upgrade further.

**Comment by nickvergessen** [comment]
I guess the reason is you are still on PHP 7.2, in that case an error/warning should be shown at the top of the basic settings.
* Update PHP to 7.4
* Then you can upgrade to Nextcloud 21, 22, 23, 24
* Then upgrade to PHP 8.1
* Then you can upgrade to Nextcloud 25, 26

**Comment by VitoAliberti** [comment]
> I guess the reason is you are still on PHP 7.2, in that case an error/warning should be shown at the top of the basic settings.
> 
> * Update PHP to 7.4
> * Then you can upgrade to Nextcloud 21, 22, 23, 24
> * Then upgrade to PHP 8.1
> * Then you can upgrade to Nextcloud 25, 26

Thank you for getting back to me with steps. I will look into that.
Can you please share why I no longer have the "Default Flows" when installing the Files_AutomatedTagging app.



I used to see Default Flows but now even if I uninstall and re-install the app I get no flows:
Please review screenshot:

[](https://i.postimg.cc/br7CyQzf/No-Default-Flows.png)
