### ISSUE TITLE
Automated tagging not working on shared folders

### ISSUE THREAD

**Issue by jorgv** [nextcloud/files_automatedtagging#77]
I know is duplicating issue but since there is no way to reopen the others, I just wanted to ask if I still on the roadmap fixing #76 and #46

have the same problem with 16.0.3 still not working.

**Comment by nickvergessen** [comment]
Shared folders (as per your title) are working.

**Comment by jorgv** [comment]
Thanks for your answer @nickvergessen, Automated tagging on shared folders are not working, you can see #76 and #46 that were closed without being resolved. 

Steps to reproduce:

Creating a tag in the parent folder.
Create a file in the parent folder,

The tag from the parent folder is not being added to the file.

**Comment by nickvergessen** [comment]
Those tickets are about group folders, not shared folders.

We will keep this open so i can look again after my vacation

**Comment by jorgv** [comment]
Sorry for the misspelling, yes is about the group folders.

Thanks for looking into it.

**Comment by nickvergessen** [comment]
Just for the record, tags are not "copied" to all files that are uploaded into a folder.
See https://docs.nextcloud.com/server/stable/admin_manual/file_workflows/automated_tagging.html for an example.

So a rule you would add is:
![Bildschirmfoto von 2019-08-21 11-31-51](https://user-images.githubusercontent.com/213943/63420613-57e5bd80-c407-11e9-8afe-77722205a2e3.png)

I then created a group folder named "Parent"
Tagged the folder manually with "Tag"
Uploaded a file inside, and the file got automatically tagged with "Tag" as well.

**Comment by jorgv** [comment]
thanks for the explanation @nickvergessen, I followed these exact steps, and the result is the same. new files uploaded in Parent are not tagged with "Tag".

The parent folder is inside a Group Folder.
