### ISSUE TITLE
add more rule options

### ISSUE THREAD

**Issue by Ulli2k** [nextcloud/files_automatedtagging#82]
I plan to use nextcloud as document management system.
Therefore it would be great to use your plugin to autotag my pdf documents.
Would it be possible to add more rules to analyse document e.g. the meta data of the pdf file, the OCRed content, filename?

**Comment by gorootde** [comment]
Having rules to assign tags based on text-content would be awesome.

**Comment by clementcres** [comment]
Having rules to assign tags based on picture metadata (GPS location, date of picture, etc...) would be also awesome. It will allows us to create "Vacation album" automatically by entering the location and/or the date of our holidays (i.e. take all pictures with date > 10 August 2020 and date < 18 August 2020 and assign tag "Holiday August")

**Comment by tstreibl** [comment]
would be nice to add the userid as a tag to see which user modified or created a file or directory. I use nextcloud as a "transfer cloud" wherer users can add folders to a share; those folders are automatically transferred to a server and the user get's a notification emails together with the hash tags of all files in his folder. The webdav client api provides only the {http://owncloud.org/ns}owner-id tag, which is the user who created the share but not the user who added or modified content in the share.

**Comment by nickvergessen** [comment]
Feel free to create specific requests in https://github.com/nextcloud/server/issues as that is where the checks live.
This app only offers an action (right side of the workflow screen).
