### ISSUE TITLE
add rule parent directory of the uploaded file

### ISSUE THREAD

**Issue by phoezelle** [nextcloud/files_automatedtagging#83]
is it possible to add rule about parent directory of a file.
thanks

**Comment by nickvergessen** [comment]
Which rule exactly are you looking for?

**Comment by phoezelle** [comment]
just a text comparison of parent folder name where the file are uploaded. Could be for example :

If parent directory's name is "img" add tag img 

if parent directory's name is "admin-folder" add tag admin. 
(but I don't want all files aded by users in admin group are tagged admin, only these in "admin-folder, so I can't used rule about group member)

thanks

**Comment by nickvergessen** [comment]
Just add a tag on those folders and then tag all children with img wenn tag img-folder is assigned
