### ISSUE TITLE
Tags are not assigned if "Request user agent" is "Thunderbird & Outlook addons"

### ISSUE THREAD

**Issue by v-bulynkin** [nextcloud/files_automatedtagging#84]
### Steps to reproduce
1. Create a new restricted collaborative tag
2. Create new automatic tagging group with the tag above
3. Select "Request user agent" -> is -> Thunderbird & Outlook addons

### Expected behaviour
The tag should be assigned to new files which are uploaded through Outlook addon.

### Actual behaviour
Files uploads but the tag is not added.
If you set "Request user agent" -> match -> `((Mozilla\/).*( \().*(\))( Nextcloud-Outlook v).*)` all works properly.

## Server configuration detail

**Operating system:** Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.15

**PHP version:** 7.3.4-2

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - bruteforcesettings: 1.4.0
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_automatedtagging: 1.7.0
 - files_pdfviewer: 1.6.0
 - files_retention: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "10.1.0.57",
        "vmls-nextcloud1",
        "cloud",
        "cloud.domain.ru",
        "10.1.0.60",
        "nlb",
        "nlb.domain.ru"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "overwrite.cli.url": "http:\/\/10.1.0.57",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "logtimezone": "Europe\/Moscow",
    "simpleSignUpLink.shown": false,
    "lost_password_link": "disabled",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by nickvergessen** [comment]
Can you check your log file whether the user agent of the outlook plugin is in there somewhere? It seems to not match the defined one anymore? The pattern that was agreed on is `/^Mozilla\/5\.0 \([A-Za-z ]+\) Nextcloud\-Outlook v.*$/`

**Comment by usselite** [comment]
@nickvergessen Hi Nick, just checked it myself. Seems that the pattern does not match anymore as discussed. That is because natively build information is included on the Windows identifier.

For example: User-Agent: Mozilla/5.0 (Microsoft Windows NT 10.0.18363.0) Nextcloud-Outlook v3.0.5.0

I will change it instead to, User-Agent: Mozilla/5.0 (Windows) Nextcloud-Outlook v3.0.5.0

**Comment by nickvergessen** [comment]
adjusted the regex above

**Comment by blizzz** [comment]
The regex is defined in server's `IRequest` seems to have the digits of the Windows version missing.

**Comment by v-bulynkin** [comment]
Still doesn't work on Nextcloud 21.0.2 + Outlook 2013 + Windows 10.
Where can I look at useragent?

**Comment by blizzz** [comment]
it's logged with $datadir/nextcloud.log

**Comment by v-bulynkin** [comment]
My useragent is
```
Mozilla/5.0 (Microsoft Windows NT 10.0.19042.0) Nextcloud-Outlook v2.3.1.17
```

**Comment by usselite** [comment]
Reversing the user-agent to support numbers (again) would possibly be breaking for v3 of the Outlook add-in.

**Comment by v-bulynkin** [comment]
Why not to add an option for Outlook add-ins versions before v3?

**Comment by usselite** [comment]
We do not support the v2 variant anymore. I guess technically they could get it working in this app though.

**Comment by nickvergessen** [comment]
If this is still an issue in Nextcloud 24 or later, please feel free to create a new issue in https://github.com/nextcloud/server/issues as that is where the "user agent" check code is
