### ISSUE TITLE
Automated Tagging in admin Flow not being applied to all users?

### ISSUE THREAD

**Issue by theklefti** [nextcloud/files_automatedtagging#850]
### Steps to reproduce

1. I’m trying to build a flow in my admin section that looks like this in the ADMIN workflow section to apply to all users:

![b3b0cdb637b944182c315f4e9d01e3e4d56e4e39_2_1380x702](https://github.com/nextcloud/files_automatedtagging/assets/93050216/3af640be-5173-4248-88be-d3b48e0350dc)

2. The flow I’m trying to make is to get all the files uploaded to the “Talk” folder (from the Talk app) which has the tag “TalkFolder” to be switched to a tag called “UploadedFromTalkApp”. This is to allow for deleting old photos using the File Retention & Automatic Deletion section here:

![e862f271c5c09d4a4b27df017d540d77a86b3b13_2_1380x384](https://github.com/nextcloud/files_automatedtagging/assets/93050216/f3e35451-6af7-4a0f-9d30-a0d9fbdbc64c)

### Expected behaviour
Tell us what should happen

ALL users who upload an image to Talk should get the new tag.

### Actual behaviour

This works totally fine for me (admin user), but I noticed when another user tries to upload an image to Talk, that file does not seem to get the new tag.

### Server configuration

**Operating system**: Linux 6.1.21-v8+ aarch64

**Web server:** nginx

**Database:** mysql

**PHP version:** 8.2.13

**Nextcloud version:** 27.1.5

**Where did you install Nextcloud from:** installed manually

**Signing status:** Using SSL?

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

Activity
Brute-force settings
Calendar
Circles
Collaborative tags
Comments
Contacts
Contracts Interaction
Dashboard
Deck
Deleted Files
Federation
File Reminderes
File Sharing
Files Automated Tagging
First run wizard
Log Reader
Monitoring
Nextcloud announcements
Nextcloud office
Notes
Notifications
Password policy
PDF viewer
Photos
Preview Generator
Privacy
Recommendations
Related Resources
Retention
Right Click
Share by mail
Support
Suspicious Login
Talk
Tasks
Text
Two-Factor TOTP Provider
Update notification
Usage survey
User Status
Versions
Weather Status

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "--CORRECT-BUT-HIDDEN--"
        ],
        "default_locale": "en_GB",
        "default_phone_region": "GB",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.5.1",
        "overwrite.cli.url": "https:\/\/www.CORRECT-BUT-HIDDEN.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "loglevel": 2,
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 10,
        "app_install_overwrite": [
            "issuetemplate"
        ]
    }
}

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:* no

**Comment by theklefti** [comment]
Hi, 

Thanks for your feedback. It's a small family server so the intrusiveness is fine for our use-case - the 7 days is just for testing anyway.

What would be the most effective way of essentially telling the Talk app to delete all of its content older than X days. This seems like a fairly essential setting which exists in pretty much all other chat / talk servers. Am I missing something?

Thanks.

**Comment by nickvergessen** [comment]
> What would be the most effective way of essentially telling the Talk app to delete all of its content older than X days. This seems like a fairly essential setting which exists in pretty much all other chat / talk servers. Am I missing something?

Well in that case continue as mentioned above. Set up an automated tagging rule that tags all folders with the name "Talk" as "TalkFolder", then the rule from your above screenshot should work already.

**Comment by theklefti** [comment]
Hi @nickvergessen,

Appreciate the help. I've added this:

<img width="968" alt="Screenshot 2024-01-08 at 15 43 31" src="https://github.com/nextcloud/files_automatedtagging/assets/93050216/9c23febb-a0c2-4232-8156-a7730af93f4b">

Would this work if the Talk folder already exists for other users?  It looks like the only option I have for "when" is "File is changed", so unless the folder is changed somehow it seems like this wouldn't work?

Thanks!

**Comment by nickvergessen** [comment]
Folders change when their content changes, so the next upload would add it

**Comment by theklefti** [comment]
Hi @nickvergessen,

Just confirmed - it seems to be working :)

Thanks!
