### ISSUE TITLE
Automated tagging does not work since NC 28

### ISSUE THREAD

**Issue by mayonezo** [nextcloud/files_automatedtagging#870]
### Steps to reproduce
1. Set automated tagging flow

![Unbenannt](https://github.com/nextcloud/files_automatedtagging/assets/5090215/cfc6354f-346a-4db1-b1d8-af42ee21f937)

2. upload new file that matches the regular expression

### Expected behaviour
File gets tagged

### Actual behaviour
File does not get tagged. Used to work before installing NC28.

### Server configuration

**Operating system**: Debian 12 Bookworm

**Web server:** Apache2

**Database:** MariaDB 10.11.4

**PHP version:** 8.2.7

**Nextcloud version:** Nextcloud Hub 7 (28.0.2)

**Where did you install Nextcloud from:** Manual installation

**Signing status:**

```
No errors have been found.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by mayonezo** [comment]
I just found out, that the files seem to be tagged, but it only shows in the NC Android App. File Retention does not seem to find the tagged files either, they don't get removed.

**Comment by BBergerac** [comment]
The app description says that it also works for "**File is uploaded**" but this option isn't available; only "File is changed" is available. That means I cannot tag an uploaded file. BTW: ownCloud is much better in this regard; I can easily configure a notification on File uploaded.

**Comment by nickvergessen** [comment]
> Edit: Turns out that the files not getting removed is more likely the fault of the File Retention app.

Closing
