### ISSUE TITLE
PHP error with automated file tagging

### ISSUE THREAD

**Issue by falcosmash** [nextcloud/files_automatedtagging#91]
Hi the team,

Thanks to all of you for your work on this project. I contact because I recently upgraded my nextcloud instance to the 18 version.

I had the app automated file tagging installed and I think it is causing me some troubles with php. I can no longer use occ command even the maintenance mode. Every time I get this error :

PHP Fatal error:  Declaration of OCA\FilesAutomatedTagging\Operation::validateOperation($name, array $checks, $operation) must be compatible with OCP\WorkflowEngine\IOperation::validateOperation(string $name, array $checks, string $operation): void in /var/www/html/nextcloud/apps/files_automatedtagging/lib/Operation.php on line 35

My question is : how can I delete this without the occ command and moreover without the web admin interface.

I think it is not an easy action but maybe if we delete some files or if we edit some configuration file to disable this app that's why I need your help.

Thanks in advance for your answer :-)

Best regards,

**Comment by skjnldsv** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
Yeah, this app is not ready for 18 yet. You can try out this PR: https://github.com/nextcloud/files_automatedtagging/pull/85

But no garantees yet

**Comment by blizzz** [comment]
a version for 18 is released now (mind, there are related bugfixes in 18 since beta2, 3 is coming tomorrow)

**Comment by nursoda** [comment]
I just encountered the same issue when updating 17.0.2 to 18 RC2 …???

**Comment by vwbusguy** [comment]
FYI - I just had the same issue.  Tried to upgrade from 17.0.3 to 18.0.1 through the web updater and got a 500 after it did the download/extract.  I had to delete the files_automatedtagging from the filesystem in order to get past it.

**Comment by derobert** [comment]
Same issue. Disabling the app (with occ, e.g., `su -s /bin/sh - www-data -c 'php /srv/nextcloud/occ app:disable files_automatedtagging'`) let me finish the upgrade; afterwards I used occ to update it then re-enable it.

**Comment by grinapo** [comment]
Yeah, this still bites. I'd say installer shall disable these by default, since it breaks the upgrade.
